### ISSUE TITLE
Exclude reads from fastq 'background' files

### ISSUE THREAD

**Issue by adrosenbaum** [adrosenbaum/mutacc#23]
I'm starting to implement the 'export' part of the program. Here I will need to exclude certain records from a fastq file, replacing these reads with reads that spans a variant. My python implementation for this at the moment is too ineffective I think. I thought of resorting to bash one-liners a la

gunzip -c in.fastq.gz | paste - - - - | grep -v -F -f read_ids.txt | tr "\t" "\n" | gzip > out.fastq.gz

But this is not very effective for large fastq files either.
seqtk has a great functionality to extract certain reads from a fastq (seqtk subseq), but nothing doing the reverse (excluding reads).

If you have some idea how this can be solved more efficiently I will be happy to hear it!

**Comment by moonso** [comment]
I need to have more information to give some input, perhaps we can meet next week?

**Comment by adrosenbaum** [comment]
Absolutely. I will be back again on Tuesday, so if you have time then it would be appreciated!
